apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.mariadb.name }}-service
  namespace: {{ .Values.database.namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.database.mariadb.clusterPort }}
    targetPort: {{ .Values.database.mariadb.port}}
  selector:
    app: mariadb