apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-deployment
  labels:
    app:  api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: localhost:32000/node_api:v5
          ports:
            - containerPort: 5000
          env:
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mariadb-config
                key: MARIADB_DATABASE
          - name: MARIADB_USER
            valueFrom:
              configMapKeyRef:
                name: mariadb-config
                key: MARIADB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: MYSQL_PASSWORD