apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.ui.react.name }}-deployment
  labels: &labels
    app: {{ .Values.ui.appLabel }}
    type: deployment
    version: real
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name:  {{ .Values.ui.react.name }}-container
        image:  {{ .Values.ui.react.image }}
        ports:
        - containerPort:  {{ .Values.ui.react.port }}