apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.react.name }}-service
  labels:
    app: {{ .Values.ui.appLabel }}
    type: service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: {{ .Values.ui.react.nodePort }}
    port: {{ .Values.ui.react.clusterPort }}
    targetPort: {{ .Values.ui.react.port }}
  selector:
    app: {{ .Values.ui.appLabel }}
