apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name:  mariadb-container
        image:  mariadb:10.7.1-focal
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3306
        env:
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: MARIADB_DATABASE
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: MARIADB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/mariadb/data
            name: mariadbdata
      volumes:
        - name: mariadbdata
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
        
