apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: database
  name: read-pods
subjects:
- kind: User
  name: peter
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: db-pod-reader
  apiGroup: rbac.authorization.k8s.io